# Generated by Django 3.0 on 2019-12-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commit_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='head_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.IntegerField()),
                ('nextcommit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sha_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=20)),
                ('string', models.TextField()),
            ],
        ),
    ]
