# Generated by Django 3.0 on 2019-12-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191218_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit_table',
            old_name='c1',
            new_name='cc',
        ),
        migrations.RemoveField(
            model_name='sha_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='sha_table',
            name='string',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
