# Generated by Django 3.0 on 2019-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191218_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sha_table',
            name='sha',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sha_table',
            name='string',
            field=models.TextField(),
        ),
    ]
