# Generated by Django 3.0 on 2019-12-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191218_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sha_table',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sha_table',
            name='sha',
            field=models.CharField(max_length=50),
        ),
    ]
