# Generated by Django 3.0.1 on 2019-12-26 12:20

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='code_info',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='null', max_length=50), size=1000), size=1000)),
            ],
        ),
        migrations.CreateModel(
            name='commit_info',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('commit_email', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='null', max_length=50), size=1000), size=1000)),
                ('last_commit_date', models.DateField(default=datetime.date.today)),
                ('last_commit_time', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='commit_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('linenum', models.IntegerField()),
                ('key', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='null', max_length=50), size=1000), size=1000)),
            ],
        ),
        migrations.CreateModel(
            name='cred',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='headt',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('head', models.IntegerField()),
                ('nextcommit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sha_table',
            fields=[
                ('sha', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('string', models.TextField()),
            ],
        ),
    ]
