# Generated by Django 3.0.1 on 2019-12-19 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commit_table',
            fields=[
                ('codes', models.IntegerField(primary_key=True, serialize=False)),
                ('ls', models.IntegerField()),
                ('keys', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=1000)),
            ],
        ),
        migrations.CreateModel(
            name='cred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.IntegerField()),
                ('invcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='head_table',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.IntegerField()),
                ('nextcommit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sha_table',
            fields=[
                ('sha', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('string', models.TextField()),
            ],
        ),
    ]
