# Generated by Django 3.0.1 on 2019-12-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headt',
            old_name='email',
            new_name='code',
        ),
    ]
