# Generated by Django 3.0.1 on 2019-12-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='headt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('head', models.IntegerField()),
                ('nextcommit', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='head_table',
        ),
    ]
