# Generated by Django 3.0.1 on 2019-12-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0002_auto_20191219_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cred',
            name='invcode',
            field=models.CharField(max_length=50),
        ),
    ]
