# Generated by Django 3.0.1 on 2019-12-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0002_auto_20191219_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headt',
            name='id',
        ),
        migrations.AlterField(
            model_name='headt',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
