# Generated by Django 3.0.1 on 2019-12-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0003_auto_20191219_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit_table',
            old_name='codes',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='commit_table',
            old_name='keys',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='commit_table',
            old_name='ls',
            new_name='linenum',
        ),
    ]
