# Generated by Django 3.0.1 on 2019-12-19 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0003_auto_20191219_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit_table',
            name='key',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=1000), size=1000),
        ),
    ]
