# Generated by Django 3.0.1 on 2019-12-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0004_auto_20191219_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit_table',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
