# Generated by Django 3.0.1 on 2019-12-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0009_auto_20191219_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
