# Generated by Django 3.0.1 on 2019-12-19 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0010_auto_20191219_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='commit_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('linenum', models.IntegerField()),
                ('key', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='commit',
        ),
    ]
